---

- hosts: all
  become: true
  become_method: su
  become_user: root
  tasks:

  - name: install updates (CentOS)
    tags: always
    package:
      update_only: true
      update_cache: true
    when: ansible_distribution == "CentOS"

  - name: install updates (Debian)
    tags: always
    package:
        upgrade: dist
        update_cache: true
    when: ansible_distribution == "Debian"

  - name: install apache and php for CentOS servers
    tags: httpd,apach2,centos
    package:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (CentOS)
    tags: mariadb,centos
    package:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Debian)
    tags: mariadb,debian
    package:
        name: mariadb-server
        state: latest
    when: ansible_distribution == "Debian"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: mariadb,ubuntu
    package:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
