---

- hosts: all
  become: true
  become_method: "{{ become_method }}"
  tasks:

  - name: Updating all packages in Debian and Ubuntu
    tags: always
    ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]
  
  - name: Updating all packages in CentOS
    tags: always
    ansible.builtin.yum:
        update_only: yes
        update_cache: yes
    when: ansible_distribution == "CentOS"
  
  - name: Install qemu-guest-agent and unzip
    tags: always, CentOS, Debian, Ubuntu, qemu, unzip
    package:
        name:
          - qemu-guest-agent
          - unzip
        state: latest
  
- hosts: web_servers
  become: true
  become_method: "{{ become_method }}"
  tasks:
  
  - name: install apache and php on all web servers
    tags: httpd,apache2, php, libapache2-mod-php
    package:
      name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
      state: latest
  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644  
    

- hosts: db_servers
  become: true
  become_method: "{{ become_method }}"
  tasks:

    - name: install mariadb package
      tags: mariadb, mariadb-server
      package:
        name: mariadb-server
        state: latest

- hosts: file_servers
  become: true
  become_method: "{{ become_method }}"
  tasks:

    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
